
// Créer un restaurant
POST http://localhost:5001/api/restaurants
Content-Type: application/json

{
  "restaurant_name": "Chez Mario",
  "restaurant_address": "6 avenue général Leclerc, 69140 Rillieux-la-pape, France",
  "restaurant_phone": "0781655198",
  "restaurant_email": "maric@dksqdsq.fr",
  "opening_hours": "Lundi - Samedi : 12h - 14h, 19h - 23h",
  "restaurant_type": "Italien, Kebab",
  "average_rating": 4.7,
  "owner_id": "10644621-a798-4054-b2c0-4203e9eecd17"
}


###

// Get All Restaurants
GET http://localhost:5001/api/restaurants

### 
// Get Restaurant By Id
GET http://localhost:5001/api/restaurants/3bd46bae-92ef-4e3a-af1c-7a2e28e47a07

### 

// By owner ID
GET http://localhost:5001/api/restaurants?owner=4d42a145-3804-4a04-a73a-5996517f68a0

###

GET http://localhost:5001/api/restaurants?type=italien

###
// Update Restaurant
PUT http://localhost:5001/api/restaurants/3bd46bae-92ef-4e3a-af1c-7a2e28e47a07
Content-Type: application/json

{
  "restaurant_name": "Luigi Pizza Updated",
  "opening_hours": "Tous les jours : 11h - 23h"
}

### 


// Delete Restaurant
DELETE http://localhost:5001/api/restaurants/3bd46bae-92ef-4e3a-af1c-7a2e28e47a07

###
// Get All Categories
GET http://localhost:5001/api/categories

###

// Create a category
POST http://localhost:5001/api/categories
Content-Type: application/json

{
  "name": "Pizza",
  "restaurant_id": "654ebbd7-667b-46d2-b288-468d9f5595b1"
}


### 



DELETE http://localhost:5001/api/categories


###

POST http://localhost:5001/api/articles 
Content-Type: application/json

 {
    "name": "Pizza Margherita",
    "desc": "Tomate, mozzarella, basilic",
    "price": 9.99,
    "categoryIds": ["90e99467-c55f-4871-9492-7d059f867df7", "95150b2f-9b10-460c-bbb8-3c71a0f88fb3"]
  }

###

POST http://localhost:5001/api/ingredients
Content-Type: application/json

{
  "name": "Mozzarella",
  "restaurant_id": "83ae1cc3-c436-48ab-8d45-d5c6e7485e29"
}

###

GET http://localhost:5001/api/ingredients

###
GET http://localhost:5001/api/articles
###

POST http://localhost:5001/api/articles
Content-Type: application/json

{
  "name": "Pizza 4 Pepperoni",
  "desc": "avec supplément gorgonzola",
  "price": 13.49,
  "categoryIds": ["90e99467-c55f-4871-9492-7d059f867df7"],
  "ingredients": [
    {
      "ingredient_id": "ffd269fb-68c2-475e-a39e-e9eb27b16eaa",
      "is_optional": false,
      "extra_price": 0.50
    }
  ]
}
