
// Créer un restaurant
POST http://localhost:5001/api/restaurants
Content-Type: application/json

{
  "restaurant_name": "Chez Mario",
  "restaurant_address": "6 avenue général Leclerc, 69140 Rillieux-la-pape, France",
  "restaurant_phone": "0781655198",
  "restaurant_email": "maric@dksqdsq.fr",
  "opening_hours": "Lundi - Samedi : 12h - 14h, 19h - 23h",
  "restaurant_type": "Italien, Kebab",
  "average_rating": 4.7,
  "owner_id": "4d42a145-3804-4a04-a73a-5996517f68a0"
}


###

// Get All Restaurants
GET http://localhost:5001/api/restaurants

### 
// Get Restaurant By Id
GET http://localhost:5001/api/restaurants/3bd46bae-92ef-4e3a-af1c-7a2e28e47a07

### 

// By owner ID
GET http://localhost:5001/api/restaurants?owner=4d42a145-3804-4a04-a73a-5996517f68a0

###

GET http://localhost:5001/api/restaurants?type=italien

###
// Update Restaurant
PUT http://localhost:5001/api/restaurants/3bd46bae-92ef-4e3a-af1c-7a2e28e47a07
Content-Type: application/json

{
  "restaurant_name": "Luigi Pizza Updated",
  "opening_hours": "Tous les jours : 11h - 23h"
}

### 


// Delete Restaurant
DELETE http://localhost:5001/api/restaurants/3bd46bae-92ef-4e3a-af1c-7a2e28e47a07

###
// Get All Categories
GET http://localhost:5001/api/categories

###

// Create a category
POST http://localhost:5001/api/categories
Content-Type: application/json

{
  "name": "Dessert",
  "restaurant_id": "9f8a92cd-da79-4c78-b06b-3e5f6efb9777"
}


### 

// Create an ingredient

POST http://localhost:5001/api/ingredients
Content-Type: application/json

{
  "name": "Fromage"
}