export const INCORRECT_EMAIL_CODE = 'INCORRECT_EMAIL';
export const INCORRECT_PASSWORD_CODE = 'INCORRECT_PASSWORD';
export const TECHNICAL_ERROR_CODE = 'TECHNICAL_ERROR';
export const EMAIL_ALREADY_EXISTS_CODE = 'EMAIL_ALREADY_EXISTS';