
// Register
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "zecxwcxwb",
  "email": "bob@email.com",
  "phone": "0781548795",
  "type": 1,
  "password": "bob"
}

###

// Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email":"bob@email.com",
    "password":"bob"
}

###
// Change password

POST http://localhost:5000/api/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNTkyZTUzMWUtNmZkZS00MDdmLWI0OWEtZjAwYTMyMWJiNjZiIiwidXNlcl9uYW1lIjoiemVjeHdjeHdiIiwidXNlcl9lbWFpbCI6ImJvYkBlbWFpbC5jb20iLCJpYXQiOjE3NDMyNjAxNDEsImV4cCI6MTc0MzI2MDE2MX0.8U-5wf-GClg89Sq88BOxIBUBq7U7J5--NMIQgL3Lk5Q

{
  "oldPassword": "bob",
  "newPassword": "bobby"
}
###

GET http://localhost:5000/api/users/user-types