
// Register
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "anas",
  "email": "anasfood@email.com",
  "phone": "07814448795",
  "type": 3,
  "password": "bob"
}

###

// Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email":"anasfood@email.com",
    "password":"bob"
}

###
// Change password

POST http://localhost:5000/api/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWQzZDE4NDAtNTVkMi00NDc2LTg2M2EtYzlmZDA2ZWViYTUzIiwidXNlcl9uYW1lIjoiYW5hcyIsInVzZXJfZW1haWwiOiJhbmFzZm9vZEBlbWFpbC5jb20iLCJpYXQiOjE3NDM1OTYwMjgsImV4cCI6MTc0MzU5NjA0OH0.TX2PYJU0pSl0z4Vt_RBitAd2UX-IIUiw1T241TjZA3I

{
  "oldPassword": "bob",
  "newPassword": "bobby"
}
###

GET http://localhost:5000/api/users/user-types

###

// get specific user 
GET http://localhost:5000/api/users/9d3d1840-55d2-4476-863a-c9fd06eeba53

###

GET http://localhost:5000/api/users