### Get Orders by User ID
GET http://localhost:5002/api/orders/user/{userId}
Content-Type: : application/json

### 
POST http://localhost:5002/api/promos
Content-Type: application/json

{
  "id": "9999-9999-9999-9999",
  "code": "SUMMER25",
  "discount": 25,
  "validUntil": "2025-07-01T23:59:59.000Z"
}

### Get All Promos
GET http://localhost:5002/api/promos    
Content-Type: application/json

###

POST http://localhost:5002/api/orders
Content-Type: application/json

{
  "user_id": "865505d1-296a-450c-88b7-c4414375f15d",
  "promoCodeId": "9999-9999-9999-9999",
  "articles": [
    {
      "article_id": "92a7b28c-29f5-4005-b0a9-6f30e8cddb7c",
      "name": "Cheeseburger",
      "price": 8.99,
      "image": "https://img.com/burger.jpg",
      "quantity": 2,
      "restaurant_id": "ff6df79a-5917-4c00-a26e-15043b28c9b8",
      "restaurant_name": "Burger Palace",
      "supplements": [
        { "name": "Sauce extra", "extra_price": 0.5 },
        { "name": "Fromage en plus", "extra_price": 1 }
      ],
      "removed_ingredients": [
        { "name": "Oignons" },
        { "name": "Cornichons" }
      ],
      "selectedOptions": [
        { "name": "Taille", "value": "XL", "extra_price": 2 },
        { "name": "Pain", "value": "Brioché", "extra_price": 0 }
      ]
    }
  ]
}



### Get All Orders
GET http://localhost:5002/api/orders
Content-Type: application/json
